# -*- coding: utf-8 -*-
"""agentes_ml_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpu0d6_nQFeSTF-TwY4KdlKBhWGNj5Di

# 🤖 Pipeline de 3 Agentes ML — Dataset Titanic

```
Dataset CSV (Titanic)
     ↓
AGENTE 1 - Normalizador   → limpia, imputa, escala, codifica
     ↓ dataset limpio
AGENTE 2 - Entrenador     → aplica validación, entrena, selecciona modelo
     ↓ métricas + modelo
AGENTE 3 - Comunicador    → genera reporte en lenguaje natural (Claude)
```

**Objetivo:** Predecir si un pasajero del Titanic **sobrevivió** (`1`) o **no** (`0`).

> ⚠️ **Antes de ejecutar:** Pegá tu API Key de Anthropic en la celda de configuración.
> Conseguila gratis en [console.anthropic.com](https://console.anthropic.com/)

## 📦 Paso 1 — Instalar dependencias
"""

!pip install pandas scikit-learn requests --quiet
print('✅ Dependencias instaladas')

"""## 🔑 Paso 2 — Tu API Key de Anthropic (Claude)"""

ANTHROPIC_API_KEY = 'sk-ant-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'  # ← Reemplazá esto
print('✅ API Key configurada')

"""## 🔧 Paso 3 — Importaciones"""

import os
import json
import requests
import pandas as pd
import numpy as np

from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

print('✅ Importaciones exitosas')

"""## 📊 Paso 4 — Cargar el dataset Titanic"""

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df_raw = pd.read_csv(url)
df_raw = df_raw[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Survived']]

print('📋 Dataset Titanic cargado:')
print(f'  Filas: {len(df_raw)} | Columnas: {len(df_raw.columns)}')
print(f'  Valores faltantes: {df_raw.isnull().sum().sum()}')
display(df_raw.head(10))

"""---
## 🤖 AGENTE 1 — Normalizador
> Limpia, imputa, escala y codifica el dataset
"""

class AgenteNormalizador:
    def __init__(self, target_col):
        self.target_col = target_col
        self.scaler = StandardScaler()
        self.imputer_num = SimpleImputer(strategy='median')
        self.imputer_cat = SimpleImputer(strategy='most_frequent')
        self.label_encoders = {}

    def ejecutar(self, df):
        print('🔄 [AGENTE 1] Iniciando normalización...')
        df = df.copy()

        y = df[self.target_col]
        X = df.drop(columns=[self.target_col])

        cols_num = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
        cols_cat = X.select_dtypes(include=['object']).columns.tolist()

        if cols_num:
            X[cols_num] = self.imputer_num.fit_transform(X[cols_num])
            print(f'  ✔ Imputadas columnas numéricas: {cols_num}')

        if cols_cat:
            X[cols_cat] = self.imputer_cat.fit_transform(X[cols_cat])
            for col in cols_cat:
                le = LabelEncoder()
                X[col] = le.fit_transform(X[col])
                self.label_encoders[col] = le
            print(f'  ✔ Codificadas columnas categóricas: {cols_cat}')

        if cols_num:
            X[cols_num] = self.scaler.fit_transform(X[cols_num])
            print(f'  ✔ Escaladas columnas numéricas')

        df_limpio = X.copy()
        df_limpio[self.target_col] = y.values
        print(f'  ✅ Dataset limpio: {df_limpio.shape[0]} filas × {df_limpio.shape[1]} columnas')
        return df_limpio


TARGET = 'Survived'
agente1 = AgenteNormalizador(target_col=TARGET)
df_limpio = agente1.ejecutar(df_raw)

print('\n📋 Dataset limpio:')
display(df_limpio.head())

"""---
## 🤖 AGENTE 2 — Entrenador
> Compara modelos con validación cruzada y selecciona el mejor
"""

class AgenteEntrenador:
    def __init__(self, target_col, cv_folds=5):
        self.target_col = target_col
        self.cv_folds = cv_folds
        self.modelos_candidatos = {
            'Regresión Logística': LogisticRegression(max_iter=1000, random_state=42),
            'Random Forest':       RandomForestClassifier(n_estimators=100, random_state=42),
            'Gradient Boosting':   GradientBoostingClassifier(random_state=42),
            'SVM':                 SVC(kernel='rbf', random_state=42)
        }
        self.mejor_modelo = None
        self.mejor_nombre = None
        self.resultados = {}

    def ejecutar(self, df):
        print('🔄 [AGENTE 2] Iniciando entrenamiento...')

        X = df.drop(columns=[self.target_col]).values
        y = df[self.target_col].values

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )
        print(f'  Train: {len(X_train)} | Test: {len(X_test)} | CV: {self.cv_folds} folds\n')

        mejor_score = -np.inf

        for nombre, modelo in self.modelos_candidatos.items():
            scores = cross_val_score(modelo, X_train, y_train, cv=self.cv_folds, scoring='accuracy')
            self.resultados[nombre] = {
                'cv_mean': round(float(scores.mean()), 4),
                'cv_std':  round(float(scores.std()),  4)
            }
            print(f'  📊 {nombre:<25} Accuracy: {scores.mean():.4f} ± {scores.std():.4f}')
            if scores.mean() > mejor_score:
                mejor_score = scores.mean()
                self.mejor_nombre = nombre
                self.mejor_modelo = modelo

        self.mejor_modelo.fit(X_train, y_train)
        y_pred = self.mejor_modelo.predict(X_test)
        reporte = classification_report(y_test, y_pred, output_dict=True)

        metricas = {
            'modelo_seleccionado': self.mejor_nombre,
            'accuracy_test':       round(float(accuracy_score(y_test, y_pred)), 4),
            'cv_accuracy_mean':    self.resultados[self.mejor_nombre]['cv_mean'],
            'cv_accuracy_std':     self.resultados[self.mejor_nombre]['cv_std'],
            'precision_macro':     round(reporte['macro avg']['precision'], 4),
            'recall_macro':        round(reporte['macro avg']['recall'],    4),
            'f1_macro':            round(reporte['macro avg']['f1-score'],  4),
            'comparacion_modelos': self.resultados
        }

        print(f'\n  🏆 Mejor modelo: {self.mejor_nombre}')
        print(f'  ✅ Accuracy en test: {metricas["accuracy_test"]}')
        return self.mejor_modelo, metricas


agente2 = AgenteEntrenador(target_col=TARGET)
modelo_final, metricas = agente2.ejecutar(df_limpio)

print('\n📈 Métricas resumen:')
resumen = {k: v for k, v in metricas.items() if k != 'comparacion_modelos'}
print(json.dumps(resumen, indent=2, ensure_ascii=False))

"""---
## 🤖 AGENTE 3 — Comunicador (Claude / Anthropic)
> Genera el reporte final en lenguaje natural
"""

class AgenteComunicador:
    API_URL = 'https://api.anthropic.com/v1/messages'
    MODEL   = 'claude-instant-1.2' # Changed to a more basic model for debugging

    def __init__(self, api_key):
        if not api_key or 'XXXX' in api_key:
            raise ValueError(
                '❌ Falta la API Key de Anthropic.\n'
                '   Conseguila en https://console.anthropic.com/ y pegala en el Paso 2.'
            )
        self.api_key = api_key

    def ejecutar(self, metricas, contexto=''):
        print('🔄 [AGENTE 3] Generando reporte con Claude...\n')

        prompt = f"""Sos un analista de datos experto. Analizá los resultados de este pipeline
de machine learning y generá un reporte ejecutivo claro en español.

Contexto: {contexto}

Métricas:
{json.dumps(metricas, indent=2, ensure_ascii=False)}

El reporte debe incluir:
1. Resumen ejecutivo (2-3 oraciones)
2. Modelo seleccionado y por qué ganó
3. Qué significan los números (accuracy, precision, recall, F1) en términos simples
4. Comparación breve con los otros modelos
5. Conclusión y recomendación final

Usá lenguaje accesible para alguien sin experiencia técnica."""

        headers = {
            'x-api-key':         self.api_key,
            'anthropic-version': '2023-06-01',
            'content-type':      'application/json'
        }
        payload = {
            'model':    self.MODEL,
            'max_tokens': 1024,
            'messages': [{'role': 'user', 'content': prompt}]
        }

        response = requests.post(self.API_URL, headers=headers, json=payload, timeout=60)
        response.raise_for_status()
        return response.json()['content'][0]['text']

# Correct the API key if it has a duplicated prefix
if ANTHROPIC_API_KEY.startswith('sk-ant-sk-ant-'):
    ANTHROPIC_API_KEY = ANTHROPIC_API_KEY.replace('sk-ant-sk-ant-', 'sk-ant-', 1)

agente3 = AgenteComunicador(api_key=ANTHROPIC_API_KEY)
reporte = agente3.ejecutar(
    metricas=metricas,
    contexto='Predicción de supervivencia de pasajeros del Titanic'
)

print('=' * 70)
print('📄 REPORTE EJECUTIVO')
print('=' * 70)
print(reporte)
print('=' * 70)